### PR TITLE
Verify FILE_CKSUM (sha256) in pkg_summary(5) on download.

### PR DESCRIPTION
**Pull request by riastradh**
This is important for detecting version rollback attacks -- verifying a signature on the package itself doesn't help, because the old one also has a valid signature.

Relies on patch proposed for pkg_install to make `pkg_info -X` generate the FILE_CKSUM lines: https://mail-index.NetBSD.org/tech-pkg/2026/01/06/msg031853.html

(Based on https://github.com/NetBSDfr/pkgin/pull/140 to make schema changes easier and more reliable.)

### CODE REVIEW

**Comment by jperkin** [comment]
I have a couple of issues with this.

Firstly it breaks builds outside of pkgsrc:

```
$ make
/Library/Developer/CommandLineTools/usr/bin/make  all-am
  CC       pkgin-actions.o
actions.c:45:10: fatal error: 'sha2.h' file not found
   45 | #include <sha2.h>
      |          ^~~~~~~~
1 error generated.
make[1]: *** [pkgin-actions.o] Error 1
make: *** [all] Error 2
```

I've put a reasonable amount of effort into making pkgin build separately from pkgsrc, and would like to retain that. There are some options for pulling in a compat sha2 if the system doesn't provide one but they either use a different API or end up pulling in quite a lot more code. I'd need to investigate this further.

Secondly I'm not keen on sha256 being hardcoded in a bunch of places, and have an aversion to spaces in column names. Given the pkg_summary format allows for arbitrary hashes, I think I'd prefer a separate table where these are stored along with an associated hash per entry for extensibility.

I'm happy to work on this, but just wanted to post something to say that I am looking at this, as I need to cut a new pkgin release now for the pkgtools upgrade issue and this will have to be deferred until later.  I have added initial `FILE_CKSUM` to pkgsrc-rs so have a test-bed for this, and am looking to extend that to support different hash types.

**Comment by riastradh** [comment]
> I've put a reasonable amount of effort into making pkgin build separately from pkgsrc, and would like to retain that. There are some options for pulling in a compat sha2 if the system doesn't provide one but they either use a different API or end up pulling in quite a lot more code.

Sorry -- I didn't test it, but I did add a libnbcompat fallback, and I'm a little surprised that didn't work because there are already libnbcompat fallbacks for other things in pkgin.  Will investigate when I have a chance.

If nothing else, we can just pull in a portable C SHA-256 from NetBSD libc.  Not perfect but enough to get it working and able to be improved later, costing around only 12 KiB of text (probably half that if we strip out SHA-512 and SHA-384 too).

> Secondly I'm not keen on sha256 being hardcoded in a bunch of places, and have an aversion to spaces in column names. Given the pkg_summary format allows for arbitrary hashes, I think I'd prefer a separate table where these are stored along with an associated hash per entry for extensibility.

I appreciate the concern for hash agility, but does the perfect need to be the enemy of the good here and hold up a security measure?

Here's the considerations that went into the choices I made:

1. The database in question is a cache.  We don't need to worry too much about the names of columns used internally by pkgin because we can just blow the database away and recreate it if need be (especially if https://github.com/NetBSDfr/pkgin/pull/140 is merged).  The pkg_summary file format is not a cache, but it already has the necessary agility and has for decades.
2. Using a space in the column name avoided the possibility of accidentally colliding with any existing pkg_summary keys.  (But I would be fine with changing it to FILE_CKSUM_sha256 or something if that makes it easier.)
3. As a practical matter, SHA-256 is adequate for security (length extension attacks are irrelevant here), and provides the best path for hardware acceleration to speed up verification later.
4. Adding another table would have made a much larger patch to add and apply queries for managing the table; this fit more easily into the existing logic.
5. This patch is much simpler than changes that would introduce a hash abstraction, implement the hash abstraction for several hashes, apply the hash abstraction to whatever set of hashes are actually used in the summary file, test it all, and so on.  (Do you test _every_ hash, or create a user configuration knob for _which_ hashes to test, or what?)

That said, the patch at the very least already identifies all the places where you will need to substitute "hash" for "sha256" in order to do (5) if desired later, making it easy to do that change if you want.

**Comment by riastradh** [comment]
I reworked this a little bit.  The updated patch:

1. provides the portable SHA-256 code itself;
2. isolates use of SHA-256 to one file, pkghash.c, to make it easy to adapt to other SHA-256 implementations in the future;
3. abstracts the hash verification through an internal pkghash_verify_init/update/final or pkghash_verify_file API;
4. otherwise mentions SHA-256 only in naming the column to match the pkg_summary file in pkgdb.sql and pkgindb_queries.c.

It doesn't create and populate a whole separate table of hashes, though, which would make the change substantially larger for what I think is rather low value right now.  Is this abstraction enough?

**Comment by riastradh** [comment]
Tested by running pkgin-test-suite with https://github.com/TritonDataCenter/pkgin-test-suite/pull/4 modified to _require_ the `Hash mismatch` error messages rather than merely _allow_ them in place of the `size does not match pkg_summary` error messages.

**Comment by riastradh** [comment]
Updated to fix a mistake in the logic to decide whether to re-download a package that we already have cached: if there is a hash in the pkg_summary, and it doesn't match the file, then the updated version always re-downloads; previous version would accept a bad hash if the size and date matched.
